config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  resource :profile, only: [:show] do
    get :edit_to_google
  end

  resources :pools, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :trainings, only: [:new, :create]

  resources :programs, only: [:new, :create, :edit, :update, :destroy] do
    get :send_to_google
    get :delete_to_google
    resources :cards, only: [:index, :show, :new, :create, :edit, :update] do
    end
  end
end

app/models/pool.rb
# == Schema Information
#
# Table name: pools
#
#  id            :integer          not null, primary key
#  address       :string
#  opening_times :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  name          :string
#  size          :integer
#  open          :boolean          default(TRUE)
#  latitude      :float
#  longitude     :float
#  price         :integer
#  treatment     :string
#  lane          :integer
#  metro         :string
#  phone         :string
#

class Pool < ApplicationRecord
  has_many :cards
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  def index
    @pool = Pool.new
    @pools = Pool.all

    # Permet de lire les coordonnees pour lister les piscines sur gmap
    @pools_gmap = Pool.where.not(latitude: nil, longitude: nil)
    @markers = @pools_gmap.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end

  def new
  end

  def create
    @pool = Pool.create(pool_params)
    redirect_to pools_path
  end

  def edit
    @pool = Pool.find(params[:id])
  end

  def update
    @pool = Pool.find(params[:id])
    @pool.update(pool_params)
    redirect_to pools_path
  end

  def destroy
    @pool = Pool.find(params[:id])
    @pool.destroy
    redirect_to pools_path
  end


  private
  def pool_params
    params.require(:pool).permit(:name,
                                 :address,
                                 :opening_times,
                                 :size,
                                 :open,
                                 :price,
                                 :phone,
                                 :metro,
                                 :lane,
                                 :treatment)
  end
end

app/views/pools/_map_box.html.erb
<div class="map-box">

<%= pool.opening_times %>
<%= pool.metro %>

</div>

app/views/pools/edit.html.erb
<h1 class="text-center" >Update</h1>
<div class="container">
  <%= link_to 'Retour', pools_path %>
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <%= simple_form_for @pool do |p| %>
        <%= p.input :name %>
        <%= p.input :address %>
        <%= p.input :open, as: :select %>
        <%= p.input :opening_times %>
        <%= p.input :price %>
        <%= p.input :phone %>
        <%= p.input :metro %>
        <%= p.input :size %>
        <%= p.input :lane %>
        <%= p.input :treatment %>
        <%= p.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/pools/index.html.erb
<!-- carte de la liste des piscines parisiennes -->
<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>">
</div>

<!-- formulaire pour ajouter une piscine en back -->
<div class="display-pools">
    <div class="col-xs-12 col-md-6">
      <ul>
        <% @pools.each do |pool| %>
          <li>
            <h4><em><%= pool.name %> :</em></h4>
            <p>
              <strong>Adresse</strong> : <%= pool.address %>
            </p>
            <p>
              <strong>Téléphone</strong> : <%= pool.phone %>
            </p>
            <p>
              <strong>Métro</strong> : <%= pool.metro %>
            </p>
            <p>
              <strong>Horaires</strong> : <%= pool.opening_times %>
            </p>
            <% if pool.open == true %>
            <p>
              <strong>Piscine ouverte</strong> : <%= image_tag 'open.png' %>
            </p>
            <% else %>
              <p>
                <strong>Piscine fermée</strong> : <%= image_tag 'close.png' %>
              </p>
            <% end %>
              <p>
                <strong>Horaires</strong> : <%= pool.opening_times %>
              </p>

            <em>Détails :</em>
            <p>
              <strong>Longueur bassin</strong> : <%= pool.size %>m
            </p>
            <p>
              <strong>Prix</strong> : <%= pool.price %>€
            </p>
            <p>
              <strong>Traitement de l'eau</strong> : <%= pool.treatment %>
            </p>
            <p>
              <strong>Nombre de couloirs de nage</strong> : <%= pool.lane %>
            </p>
            <%= link_to 'Edit', edit_pool_path(pool.id) %> |
            <%= link_to 'Supprimer', pool_path(pool.id),
              data: { confirm: 'Tu es certain de vouloir faire ça jeune inconscient ?' }, method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-xs-12 col-md-6">
      <%= simple_form_for @pool do |p| %>
        <%= p.input :name %>
        <%= p.input :address %>
        <%= p.input :open, as: :select %>
        <%= p.input :opening_times %>
        <%= p.input :price %>
        <%= p.input :phone %>
        <%= p.input :metro %>
        <%= p.input :size %>
        <%= p.input :lane %>
        <%= p.input :treatment %>
        <%= p.button :submit %>
      <% end %>
    </div>
</div>