config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  resource :profile, only: [:show] do
    get :edit_to_google
  end

  resources :pools, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :trainings, only: [:new, :create]

  resources :programs, only: [:new, :create, :edit, :update, :destroy] do
    get :send_to_google
    get :delete_to_google
    resources :cards, only: [:index, :show, :new, :create, :edit, :update] do
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
    @geocoder_result = request.location

    @program = Program.where(user: current_user).last
    @pools = Pool.where.not(latitude: nil, longitude: nil)
    @markers = @pools.map do |pool|
      {
        lat: pool.latitude,
        lng: pool.longitude,
        icon: ActionController::Base.helpers.asset_path('open.png')
      }
    end

    @geocoder_result.data['lat'] = 48.864848
    @geocoder_result.data['lng'] = 2.379853
    @markers << @geocoder_result.data
    @pool_near_me = Pool.near([@geocoder_result.data['lat'], @geocoder_result.data['lng']], 1.2)


    pools_array = []
    user_position = []
    user_position << @markers.last["lat"]
    user_position << @markers.last["lng"]

    @pool_near_me.each do |pool|
      one_pool = []
      one_pool << pool.latitude
      one_pool << pool.longitude
      pools_array << one_pool
    end

    how_far = Geocoder::Calculations.distance_between(user_position, pools_array[0])
    @distance_from_user =  how_far * 1.60934
  end
end

app/views/profiles/_editUserProgramPartial.html.erb
_editUserProgramPartial.html.erb

app/views/profiles/_poolspartial.html.erb
_poolspartial.html.erb

app/views/profiles/show.html.erb
<% if params[:sweetalert] %>
  <span id="sweetalert-trigger"></span>
<% end %>
<div class="profile-container">
  <div class="profile-header">
    <% if current_user.image %>
     <%= image_tag current_user.image, class: "avatar-big" %>
      <% else %>
      <%= image_tag "placeholder-avatar.jpg", width: 100 %>
     <% end %>
  </div>


  <div class="profile-id">
    <% if current_user.first_name %>
      <h4><%= current_user.first_name.upcase %></h4>
    <% else %>
      <h4>Nageur de compet'</h4>
    <% end %>
    <p><i class="fa fa-envelope" aria-hidden="true"></i>
 <%= current_user.email %> </p>
  </div>

  <div class="profile-nav">
    <div class="nav-piscines nav-active">
      <h4> Piscines </h4>
    </div>
    <div class="nav-programme">
      <h4> Programme </h4>
    </div>
  </div>

  <% if Program.where(:user_id == current_user).empty? %>
    <div class="pools-tab" >
      <div id="map" style="width: 100%; height: 300px;"
      data-markers="<%= @markers.to_json %>">
      </div>
    </div>

    <div class="placeholder-no-program">
      <%= link_to 'Créez votre programme', new_program_path, type: 'button',class: 'btn btn-default btn-block btn-lg btn-create-program' %>
    </div>

    <% else %>
    <div class="pools-tab" >
      <div id="map" style="width: 100%; height: 300px;"
      data-markers="<%= @markers.to_json %>">
      </div>
    <div class="space-between"></div>
      <div class="pool-card-lg-1">
        <% if @pool_near_me[0].open == true %>
          <div class="card-status">
            <p class="status-open">Ouvert</p>
          </div>
        <% else %>
          <div class="card-status">
            <p class="status-close">Fermée</p>
          </div>
        <% end %>
        <h3>
          <%= @pool_near_me[0].name.downcase.capitalize %>
        </h3>
        <p>
          <i class="fa fa-map-marker" aria-hidden="true"></i>
          <%= @pool_near_me[0].address %>
          <%= @distance_from_user.round(2) %>Km
        </p>
      </div>

        <div class="pool-card-lg-2">
          <div class="card-status">CLOSED</div>
          <h3><%= @pool_near_me[1].name.downcase.capitalize %></h3>
           <p><i class="fa fa-map-marker" aria-hidden="true"></i>
 <%= @pool_near_me[1].address %></p>
        </div>
    </div>


    <div class="program-tab hidden">
        <div class="program-level">
          <div class="title">
          <p>Niveau</p>
          </div>
          <div class="dropdown-levels">
            <h2> <%= @program.swimming_level.capitalize %> </h2>
          </div>
        </div>

        <div class="program-hours-title">
          <p>Créneaux</p>
        </div>
        <div class="program-hours-days">
          <% @program.cards_builder.keys.each do |day| %>
            <% if ["1_lundi","2_mardi","3_mercredi","4_jeudi","5_vendredi","6_samedi","7_dimanche"].include? day %>
              <div class="row">
                <div class="col-sm-12">
                  <p>
                    <%= day[2..-1].capitalize %>
                  </p>

                  <p>
                    <%= @program.cards_builder[day]["start"] %>
                    <%= @program.cards_builder[day]["end"] %>
                  </p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

        <div class="program-pools-title">
          <h2>Piscines</h2>
          <div class="closest-pool1">
            <% @program.cards_builder.each do |key, value| %>
              <% if value["okpool"]["open"] == true %>
              <% else %>
                <div class="status-bar-close">
                </div>
              <% end %>
              <div class="pool-card-large">
                <div class="title">
                  <%= value["okpool"]["name"] %>
                </div>
                <div class="address-pool">
                  <%= value["okpool"]["address"] %>
                  <%= value["okpool"]["metro"] %>
                </div>
                <div class="opening-hours">
                  <%= value["okpool"]["opening_times"] %>
                </div>
              </div>
            <% end %>
          </div>
        </div>

      <% end %>
      <div class="end-button">
        <%= link_to "Supprimer votre programme", program_path(@program), method: :delete, type: "button", class: 'btn btn-danger btn-lg bnt-block' %>
      </div>
    </div>

</div>