config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  resource :profile, only: [:show] do
    get :edit_to_google
  end

  resources :pools, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :trainings, only: [:new, :create]

  resources :programs, only: [:new, :create, :edit, :update, :destroy] do
    get :send_to_google
    get :delete_to_google
    resources :cards, only: [:index, :show, :new, :create, :edit, :update] do
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Logo -->
  <% if user_signed_in? %>

  <!-- Navbar right -->

  <!-- Profile picture with dropdown list -->


    <div class="connected-menu">
      <%= link_to root_path do %>
        Accueil
      <% end %>

      <% if Program.where(user_id: current_user.id).exists? %>
        <%= link_to profile_path do %>
          <%= t(".profile", default: "Profil") %>
        <% end %>
      <% end %>
    </div>

    <div class="connection">
      <%= link_to destroy_user_session_path, method: :delete do %>
        <%= t(".sign_out", default: "Déconnexion") %>
      <% end %>
    </div>


</div>

  <% else %>
  <!-- Login link (when logged out) -->
    <div class="connection">
      <%= link_to "Connexion", new_user_session_path %>
    </div>
  <% end %>