config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  resource :profile, only: [:show] do
    get :edit_to_google
  end

  resources :pools, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :trainings, only: [:new, :create]

  resources :programs, only: [:new, :create, :edit, :update, :destroy] do
    get :send_to_google
    get :delete_to_google
    resources :cards, only: [:index, :show, :new, :create, :edit, :update] do
    end
  end
end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id             :integer          not null, primary key
#  start_dateTime :datetime
#  end_dateTime   :datetime
#  training_id    :integer
#  pool_id        :integer
#  program_id     :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Card < ApplicationRecord
  belongs_to :training
  belongs_to :pool
  belongs_to :program
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    @cards = Card.all
    @program = Program.find(params["program_id"])
  end
end

app/views/cards/index.html.erb
<div class="wrapper-cards">

  <h2 class="form-title center-program">PROGRAMME</h2>



  <div class="go-back" id="go-back4" >
   <%= link_to edit_program_path(@program) do %>
   <h2 class="white-text">BACK</h2>
   <% end %>
   <%= image_tag "back-line.png"%>
 </div>

<div class="cardscapsule">

   <% @program.cards_builder.each_with_index do |(key, value), index| %>

   <div id="card-new">
    <h2 class="card-title"> <%= key[2..-1].capitalize %> </h2>
    <p class = "blue-content"> Votre session : <%= value["start"] %> - <%= value["end"] %> <br>
      <% if value["okpool"] %>
      <%= value["okpool"]["name"] %> <br>
      <%= value["okpool"]["metro"] %> <br>
      <%= value["okpool"]["address"] %> <br>
      <%= value["okpool"]["opening_times"] %></p>
      <% end %>
      <h6 id="program_day">Programme du jour: </h6>
      <div id="training_content">
        <p><%= value["training"] %></p>
      </div>
    </div>
    <% end %>

</div>

    <div class="export-to-google">
     <%= link_to program_send_to_google_path(@program) do %>
     <h2 class="export-text">EXPORTER <br> VERS L'AGENDA</h2>
     <%= image_tag "export-line.png", class: 'yellow-arrow'%>
     <% end %>

   </div>

</div>